import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {SECTORS,SYMBOLS,validQuote,marketState,sectorState,aligned,newsFor,compare} from './dashboard-model.mjs';
import {validate} from './validate-data.mjs';
const data=JSON.parse(fs.readFileSync(new URL('fixtures/trial-data.json',import.meta.url),'utf8'));
const fresh=()=>structuredClone(data);
const sector=(id,d)=>sectorState(SECTORS.find(s=>s.id===id),d);
test('published schema and exact roster',()=>{assert.deepEqual(validate(data),[]);assert.equal(SYMBOLS.length,19)});
test('future, stale and unavailable quotes are not current',()=>{for(const t of ['2026-09-23T20:01:00Z','2026-09-23T19:29:00Z'])assert.equal(validQuote({...data.assets.QQQ,asOf:t},data.meta),false);assert.equal(validQuote({...data.assets.QQQ,status:'unavailable'},data.meta),false)});
test('missing breadth is unknown, not neutral',()=>{const d=fresh();d.breadth.status='unavailable';assert.equal(marketState(d).state,'UNKNOWN')});
test('missing trend evidence is unknown',()=>{const d=fresh();d.assets.QQQ.vwapApprox=null;assert.equal(marketState(d).state,'UNKNOWN')});
test('three agreeing signals produce risk-on and risk-off',()=>{const d=fresh();for(const dir of ['up','down']){for(const s of ['QQQ','SPY']){d.assets[s].trend30m=dir;d.assets[s].vwapApprox=d.assets[s].price+(dir==='up'?-1:1)}d.breadth.upPct=dir==='up'?60:40;d.assets.VIX.changePct=dir==='up'?-1:1;assert.equal(marketState(d).state,dir==='up'?'RISK_ON':'RISK_OFF')}});
test('DRAM is anchor, never averaged with its peers',()=>{const d=fresh();d.assets.DRAM.changePct=2;d.assets.MU.changePct=-90;assert.equal(sector('memory',d).change,2)});
test('missing sector constituent never shrinks denominator',()=>{const d=fresh();d.assets.NBIS.status='unavailable';assert.equal(sector('cloud',d).change,null);assert.equal(sector('cloud',d).trend,'unknown');d.assets.MU.status='unavailable';assert.equal(sector('memory',d).trend,'unknown')});
test('HOOD and coins do not change equity basket',()=>{const d=fresh(),before=sector('crypto',d);for(const s of ['HOOD','BTC','ETH']){d.assets[s].changePct=99;d.assets[s].trend30m='up'}assert.equal(sector('crypto',d).change,before.change);assert.equal(sector('crypto',d).trend,before.trend);assert.equal(sector('crypto',d).coinTrend,'up')});
test('unaligned windows suppress relative comparisons',()=>{const d=fresh();d.assets.IREN.baselineAt='2026-09-22T19:30:00Z';assert.equal(sector('cloud',d).relative,null);assert.equal(aligned({},{}),false)});
test('invalid and expired news are not shown',()=>{const d=fresh();d.news.memory.publishedAt='invalid';assert.equal(newsFor(d,'memory'),null);d.news.memory.publishedAt='2026-09-01';d.news.memory.expiresAt='2026-09-02';assert.equal(newsFor(d,'memory'),null)});
test('future news must not appear before research timestamp',()=>{const d=fresh();d.news.memory.publishedAt='2099-01-01';assert.equal(newsFor(d,'memory'),null)});
test('first record and missing evidence are different',()=>{assert.equal(compare('up',null),'首次记录');assert.equal(compare('unknown','up'),'待确认');assert.equal(compare('down','up'),'恶化')});
test('validator rejects false price returns and recursive history',()=>{const d=fresh();d.assets.MU.changePct=999;assert.ok(validate(d).some(x=>x.includes('return mismatch')));d.previous={previous:{}};assert.ok(validate(d).includes('no recursive history'))});
